[package]
name = "canary"
version = "0.1.0"

[build-dependencies]
lalrpop = "0.14"

[dependencies]
failure = "0.1.0"
failure_derive = "0.1.0"
lalrpop-util = "0.14"

[dependencies.backpat]
path = "backpat"

[workspace]
